name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

  validate:
    runs-on: ubuntu-latest
    name: Validate Renovate Config
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default.json
          - renovate-config.json
          - morning.json5
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
