name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

  validate:
    runs-on: ubuntu-latest
    name: Validate Renovate Config
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default.json
          - renovate-config.json
          - morning.json5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Validate ${{ matrix.file }}
        run: pnpm renovate-config-validator ${{ matrix.file }}
