name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ../../workflows/pnpm-eslint.yml

  validate:
    runs-on: ubuntu-latest
    name: Validate Renovate Config
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - default
          - renovate-config
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@v3.0.1

      - name: Validate ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
